namespace TalkPro.Tools.SampleGenerator.Corpus;

/// <summary>
/// The only names that may appear in golden data. Every accepted speaker contains a synthetic marker
/// ("User", "Synth", "합성") so tests can verify no real-looking names slipped in.
/// </summary>
public static class SyntheticVocabulary
{
    public const string UserA = "UserA";
    public const string UserB = "User B";
    public const string UserC = "합성사용자 C";
    public const string SpecialName = "Synth#Person_04 (테스트)";
    public const string Person01 = "SyntheticPerson01";
    public const string EmojiName = "Synthetic🙂User";

    /// <summary>119 characters: accepted (limit is 128).</summary>
    public static readonly string LongName = string.Concat(Enumerable.Repeat("SyntheticLongName", 7));

    /// <summary>1,000 characters: rejected as <c>SpeakerNameTooLong</c>.</summary>
    public static readonly string TooLongName = string.Concat(Enumerable.Repeat("SyntheticTooLongName", 50));

    public static IReadOnlyList<string> AcceptedSpeakers { get; } = [UserA, UserB, UserC, SpecialName, Person01, EmojiName, LongName];

    public static IReadOnlyList<string> SyntheticMarkers { get; } = ["User", "Synth", "합성"];

    public const string RoomTitle = "합성 테스트방 01";

    public const string Notice = "100% synthetic test data generated by TalkPro.SampleGenerator. Contains no real people, numbers or conversations.";
}
